- hosts: all
  become: true

  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled

  vars:
    tomcat_version: 9.0.36
    
    tomcat_permissions_production: True
    
    tomcat_users:
      - username: "admin"
        password: "admin"
        roles: "tomcat,admin,manager,manager-gui,manager-script"
      - username: "tomcat"
        password: "tomcat"
        roles: "manager-gui,manager-script"        
  roles:
    - role: zaxos.tomcat-ansible-role